import { Brand } from "@/lib/types";
import { Creator } from "@/types/creator";

export const demoBrands: Brand[] = [
  {
    id: "demo-brand-nikon",
    uid: "demo-brand-nikon",
    name: "Nikon",
    logo: "/brand-logos/Nikon.png",
    email: "creator-partnerships@nikon-demo.com",
    industry: "tech",
    brandType: "Photography & Tech",
    targetAudience: "Photographers, videographers, travel creators",
    description: "Nikon is looking for visual storytellers to showcase camera performance, travel content, and creator workflows.",
    minIdealReach: "15k",
    collaborationType: "paid, affiliate",
    lookingFor: "photography creators, travel creators, tech reviewers",
    campaignStatus: "open",
    campaignCloseInDays: "20",
    campaignCloseDate: "2026-06-04T00:00:00.000Z",
    currentCampaign: "Frame the Journey",
    campaignDuration: "Jun 2026 - Aug 2026",
    pastCampaigns: "Lens Stories, Creator Vision",
    createdAt: new Date("2026-05-20T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-brand-nestle",
    uid: "demo-brand-nestle",
    name: "Nestle",
    logo: "/brand-logos/nestle.png",
    email: "campaigns@nestle-demo.com",
    industry: "food",
    brandType: "Food & Lifestyle",
    targetAudience: "Families, students, young professionals",
    description: "Nestle wants relatable food, family, and daily routine creators for product storytelling and recipe integration.",
    minIdealReach: "10k",
    collaborationType: "paid, barter, ambassador",
    lookingFor: "food creators, lifestyle creators, family creators",
    campaignStatus: "open",
    campaignCloseInDays: "22",
    campaignCloseDate: "2026-06-02T00:00:00.000Z",
    currentCampaign: "Everyday Taste Stories",
    campaignDuration: "Jun 2026 - Sep 2026",
    pastCampaigns: "Morning Moments, Snack Break",
    createdAt: new Date("2026-05-18T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-brand-spotify",
    uid: "demo-brand-spotify",
    name: "Spotify",
    logo: "/brand-logos/spotify.png",
    email: "brandconnect@spotify-demo.com",
    industry: "tech",
    brandType: "Music & Streaming",
    targetAudience: "Gen Z, students, music lovers, podcasters",
    description: "Spotify is seeking music, podcast, and pop-culture creators for playlist campaigns and creator-led listening trends.",
    minIdealReach: "25k",
    collaborationType: "paid, affiliate",
    lookingFor: "music creators, podcast creators, lifestyle creators",
    campaignStatus: "open",
    campaignCloseInDays: "24",
    campaignCloseDate: "2026-06-06T00:00:00.000Z",
    currentCampaign: "Playlist Pulse",
    campaignDuration: "Jun 2026 - Jul 2026",
    pastCampaigns: "Wrapped Voices, Indie Buzz",
    createdAt: new Date("2026-05-16T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-brand-zara",
    uid: "demo-brand-zara",
    name: "Zara",
    logo: "/brand-logos/Zara.png",
    email: "influencers@zara-demo.com",
    industry: "fashion",
    brandType: "Fashion",
    targetAudience: "Urban fashion shoppers and trend-driven audiences",
    description: "Zara collaborates with fashion and lifestyle creators to highlight seasonal collections, styling formats, and trend edits.",
    minIdealReach: "20k",
    collaborationType: "paid, affiliate, ambassador",
    lookingFor: "fashion creators, lifestyle creators, beauty creators",
    campaignStatus: "open",
    campaignCloseInDays: "25",
    campaignCloseDate: "2026-05-31T00:00:00.000Z",
    currentCampaign: "Summer Street Edit",
    campaignDuration: "May 2026 - Jul 2026",
    pastCampaigns: "City Layers, Minimal Moves",
    createdAt: new Date("2026-05-14T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-brand-redbull",
    uid: "demo-brand-redbull",
    name: "Red Bull",
    logo: "/brand-logos/RedBull.png",
    email: "collabs@redbull-demo.com",
    industry: "fitness",
    brandType: "Sports & Energy",
    targetAudience: "Adventure, sports, gaming, and youth culture audiences",
    description: "Red Bull looks for energetic storytelling across sports, action, college culture, and gaming experiences.",
    minIdealReach: "30k",
    collaborationType: "paid, ambassador",
    lookingFor: "fitness creators, gaming creators, travel creators",
    campaignStatus: "open",
    campaignCloseInDays: "21",
    campaignCloseDate: "2026-05-30T00:00:00.000Z",
    currentCampaign: "Fuel the Moment",
    campaignDuration: "May 2026 - Aug 2026",
    pastCampaigns: "Campus Rush, Action Mode",
    createdAt: new Date("2026-05-13T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-brand-netflix",
    uid: "demo-brand-netflix",
    name: "Netflix",
    logo: "/brand-logos/Netflix.png",
    email: "creatorstudio@netflix-demo.com",
    industry: "tech",
    brandType: "Entertainment & Streaming",
    targetAudience: "Movie lovers, pop culture communities, binge watchers",
    description: "Netflix partners with entertainment and lifestyle creators for series promotions, fan culture, and review-based campaigns.",
    minIdealReach: "50k",
    collaborationType: "paid, affiliate",
    lookingFor: "movie reviewers, lifestyle creators, comedy creators",
    campaignStatus: "open",
    campaignCloseInDays: "23",
    campaignCloseDate: "2026-06-03T00:00:00.000Z",
    currentCampaign: "Next Watch Buzz",
    campaignDuration: "Jun 2026 - Jul 2026",
    pastCampaigns: "Weekend Watchlist, Stream Scene",
    createdAt: new Date("2026-05-12T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-brand-adobe",
    uid: "demo-brand-adobe",
    name: "Adobe",
    logo: "/brand-logos/Adobe.png",
    email: "community@adobe-demo.com",
    industry: "tech",
    brandType: "Creative Software",
    targetAudience: "Designers, editors, creators, students",
    description: "Adobe works with design, editing, and educational creators to showcase creative workflows and software features.",
    minIdealReach: "15k",
    collaborationType: "paid, affiliate, ambassador",
    lookingFor: "design creators, education creators, photography creators",
    campaignStatus: "open",
    campaignCloseInDays: "26",
    campaignCloseDate: "2026-06-05T00:00:00.000Z",
    currentCampaign: "Create Without Limits",
    campaignDuration: "Jun 2026 - Sep 2026",
    pastCampaigns: "Edit Better, Design Lab",
    createdAt: new Date("2026-05-11T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
];

export const demoCreators: Creator[] = [
  {
    id: "demo-creator-nikhil",
    uid: "demo-creator-nikhil",
    name: "Nikhil",
    email: "nikhil.creator@example.com",
    platform: "youtube",
    instagramHandle: "",
    youtubeHandle: "@nikhilframes",
    youtubeChannelId: "demo-channel-nikhil",
    youtubeChannelTitle: "Nikhil Frames",
    niche: "Technology",
    followerCount: 84200,
    location: "Mumbai, India",
    bio: "Tech YouTuber creating camera, smartphone, and creator-gear reviews.",
    about: "I help audiences choose the right tech products through simple, honest breakdowns.",
    createdAt: new Date("2026-05-18T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-sahil",
    uid: "demo-creator-sahil",
    name: "Sahil",
    email: "sahil.creator@example.com",
    platform: "instagram",
    instagramHandle: "sahil.fitlife",
    niche: "Fitness & Health",
    followerCount: 18600,
    location: "Delhi, India",
    bio: "Fitness creator sharing workout routines, diet tips, and realistic transformation content.",
    about: "I create practical fitness content for college students and busy professionals.",
    createdAt: new Date("2026-05-17T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-riya",
    uid: "demo-creator-riya",
    name: "Riya",
    email: "riya.creator@example.com",
    platform: "instagram",
    instagramHandle: "riya.stylesdaily",
    niche: "Fashion & Beauty",
    followerCount: 25400,
    location: "Bengaluru, India",
    bio: "Fashion creator with styling reels, wardrobe edits, and budget-friendly trend content.",
    about: "I love helping my audience build stylish looks that are wearable and affordable.",
    createdAt: new Date("2026-05-15T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-aarav",
    uid: "demo-creator-aarav",
    name: "Aarav",
    email: "aarav.creator@example.com",
    platform: "youtube",
    instagramHandle: "",
    youtubeHandle: "@aaravtraveldiaries",
    youtubeChannelId: "demo-channel-aarav",
    youtubeChannelTitle: "Aarav Travel Diaries",
    niche: "Travel",
    followerCount: 63200,
    location: "Pune, India",
    bio: "Travel filmmaker documenting destinations, itineraries, and cinematic experiences.",
    about: "I make travel storytelling content focused on budget planning and visual inspiration.",
    createdAt: new Date("2026-05-14T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-meera",
    uid: "demo-creator-meera",
    name: "Meera",
    email: "meera.creator@example.com",
    platform: "instagram",
    instagramHandle: "meera.eats",
    niche: "Food & Cooking",
    followerCount: 12100,
    location: "Hyderabad, India",
    bio: "Food creator posting easy recipes, cafe finds, and aesthetic kitchen content.",
    about: "I simplify home cooking and discover local food spots worth sharing.",
    createdAt: new Date("2026-05-13T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-kabir",
    uid: "demo-creator-kabir",
    name: "Kabir",
    email: "kabir.creator@example.com",
    platform: "youtube",
    instagramHandle: "",
    youtubeHandle: "@kabirdesigns",
    youtubeChannelId: "demo-channel-kabir",
    youtubeChannelTitle: "Kabir Designs",
    niche: "Art & Design",
    followerCount: 41100,
    location: "Chandigarh, India",
    bio: "Design YouTuber creating tutorials on UI, branding, and creative workflows.",
    about: "I teach young creators how to improve design thinking and build strong visual portfolios.",
    createdAt: new Date("2026-05-12T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-ananya",
    uid: "demo-creator-ananya",
    name: "Ananya",
    email: "ananya.creator@example.com",
    platform: "instagram",
    instagramHandle: "ananya.lifestyleedit",
    niche: "Lifestyle",
    followerCount: 33800,
    location: "Jaipur, India",
    bio: "Lifestyle creator sharing routines, productivity, and aspirational everyday content.",
    about: "My content blends routines, beauty, travel, and lifestyle storytelling for young women.",
    createdAt: new Date("2026-05-11T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
  {
    id: "demo-creator-vedant",
    uid: "demo-creator-vedant",
    name: "Vedant",
    email: "vedant.creator@example.com",
    platform: "youtube",
    instagramHandle: "",
    youtubeHandle: "@vedantplays",
    youtubeChannelId: "demo-channel-vedant",
    youtubeChannelTitle: "Vedant Plays",
    niche: "Gaming",
    followerCount: 97300,
    location: "Ahmedabad, India",
    bio: "Gaming creator focused on live reactions, walkthroughs, and creator collaborations.",
    about: "I build highly engaged communities through competitive and community-driven gaming content.",
    createdAt: new Date("2026-05-10T00:00:00.000Z"),
    updatedAt: new Date("2026-05-27T00:00:00.000Z"),
  },
];
